version: '2'
services:
 mongodb:
  image: mongo:3.0.14
  ports:
   - "27017:27017"
  volumes:
   - ./mongo:/data/db
 web:
  image: konyk88/eduplat
  ports:
   - "3030:3030"
  volumes:
   - ./sec:/sec
  links:
   - mongodb:mongodb
  depends_on:
   - mongodb
  restart: unless-stopped
 staging:
  image: konyk88/eduplat
  ports:
   - "3030:3030"
  volumes:
   - ./sec:/sec
  restart: unless-stopped
 production:
  environment:
   NODE_ENV: production
  image: konyk88/eduplat
  ports:
   - "80:80"
  volumes:
   - ./sec:/sec
  restart: unless-stoppedd
  command: node server/server.js

  # Command to run DB & Web app
  # docker-compose run -d -p 3000:3000 webapp npm start
  # Not - Check database host name in config.js
  #"db_host": "mongodb_1"